---

# Note: if the directory does not yet exist and the user did not specify its intended
# permissions, Ansible uses the target machine's defaults to set the permissions
- name: create dest dir and set permissions if user specified them
  ansible.builtin.file:
    path: "{{ file_transfer_dest | dirname }}"
    state: directory
    mode: "{{ file_transfer_dest_dir_mode | default(omit) }}"
    owner: "{{ file_transfer_owning_user | default(omit) }}"
    group: "{{ file_transfer_owning_user | default(omit) }}"

- name: Copy file
  ansible.builtin.copy:
    src: "{{ file_transfer_src }}"
    dest: "{{ file_transfer_dest }}"
    owner: "{{ file_transfer_owning_user | default(omit) }}"
    group: "{{ file_transfer_owning_user | default(omit) }}"
    mode: "{{ file_transfer_file_mode | default(omit) }}"
