---

- name: Ensure dst dir exists
  file:
    path: "{{ file_transfer_dst_dir }}"
    state: directory
    mode: '1777'

- name: Copy file
  copy:
    src: "{{ file_transfer_src }}"
    dest: "{{ file_transfer_dst_dir ~ '/' ~ file_transfer_dst_file }}"
    owner: root
    group: root
    mode: '0644'
