---

- name: install packages (ca-certificates and unzip)
  ansible.builtin.package:
    name: 
      - ca-certificates
      - unzip
    state: present
  become: true

- name: validate web_setup.type
  assert: 
    that: 
      - web_setup.type is defined
      - web_setup.type in ['apache', 'nodejs']
    fail_msg: "web_setup.type must be either 'apache' or 'nodejs', got '{{ web_setup.type }}'"
    success_msg: "web_setup.type is set to '{{ web_setup.type }}'"

- name: Set up the web app using Apache
  when: web_setup.type == 'apache'
  block: 
    - name: install Apache
      ansible.builtin.include_role: 
        name: geerlingguy.apache
      vars:
        apache_remove_default_vhost: true 
        apache_create_vhosts: true
        apache_vhosts:       
          - servername: "{{ web_setup.servername }}" # not working for some reason??
            documentroot: "/var/www/html"
            options: "-Indexes +FollowSymLinks" # similarly nonfunctional

      # Consider using a when: clause to run these conditionally

    - name: install MySQL
      ansible.builtin.include_role: 
        name: geerlingguy.mysql
        apply: 
          become: true
      vars: 
        mysql_databases: 
          - name: traffic_db
        mysql_users: 
          - name: ansible
            host: localhost
            password: fascinatingly-complex35charAuthpass
            priv: "*.*:ALL"
          - name: webuser
            host: localhost
            password: nevergonna-GIVE-YOU-UP
            priv: "traffic_db.*:ALL"

    - name: download MySQL database file # this is the SQL dump file FOR THIS SPECIFIC SCENARIO
      ansible.builtin.get_url:
        url: "{{ web_setup.sql_url }}"
        dest: /tmp/db.sql

    - name: import records from .sql dump file
      community.mysql.mysql_db: 
        name: traffic_db
        state: import
        target: /tmp/db.sql
        login_user: ansible
        login_password: fascinatingly-complex35charAuthpass
      become: true

    - name: install PHP
      ansible.builtin.include_role: 
        name: geerlingguy.php
      vars: 
        php_packages_extra: [ 
          libapache2-mod-php,
          php-mysqli
      ] 

    - name: remove default index.html
      ansible.builtin.file: 
        path: /var/www/html/index.html
        state: absent

    - name: unzip the web app into /var/www/html
      ansible.builtin.unarchive: 
        src: "{{ web_setup.app_url }}"
        dest: /var/www/html
        remote_src: yes
        extra_opts: ["--strip-components=1"]

    - name: set permissions on web app
      ansible.builtin.file: 
        path: /var/www/html
        state: directory
        recurse: true
        mode: '0755'
        owner: www-data

- name: set up the web app using Node JS
  when: web_setup.type == 'nodejs'
  block:
    - name: install Node JS
      ansible.builtin.include_role:
        name: geerlingguy.nodejs

    - name: create nodejs user
      ansible.builtin.user: 
        name: nodejs
        system: yes
        shell: /bin/false
        home: /opt/nodejs

    - name: unzip the web app into the user's home directory
      ansible.builtin.unarchive:
        src: "{{ web_setup.url }}"
        dest: /opt/nodejs
        remote_src: yes

    - name: set permissions on web app files
      ansible.builtin.file:
        path: /opt/nodejs
        state: directory
        recurse: yes
        owner: nodejs
        group: nodejs

    - name: find server.js so we can run the server
      ansible.builtin.find:
        path: /opt/nodejs
        pattern: "server.js"
        recurse: true
        #limit: 1   # added in Ansible 2.18, and Ludus is on 2.16, so it's not supported yet
      register: server_file  # essentially a variable that has the file's path

    - name: fail if server.js is not found
      ansible.builtin.fail: 
        msg: "ERROR: server.js not found. If the Node JS web app runs under a different name, rename it to 'server.js' and try again."
      when: server_file.matched == 0

    - name: create the nodejs systemd service file
      ansible.builtin.template: 
        src: templates/service.j2
        dest: /etc/systemd/system/nodejs.service
      
    - name: reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: start NodeJS service
      ansible.builtin.service: 
        name: nodejs
        state: started
        enabled: yes
