- name: Test File Transfer
  hosts: JL-demo-webserver
  become: yes

  roles: 
    - role: file-transfer

      vars:
        file_transfer_src: "/home/jericho-ludus/ludus-configs/custom-roles/file-transfer/Jericho-demo-website"
        file_transfer_dst_dir: "/var/www/html"
        file_transfer_dst_file: "."
        file_transfer_file_owner: "www-data"
        file_transfer_file_group: "www-data"
