---
# Role variables should all be prefaced with the name of the role to avoid
# name conflicts with other roles

file_transfer_src: "temp.txt"

# This should be an absolute path, following Ansible convention 
# (see ansible.builtin.copy dest)
file_transfer_dest: "/tmp/temp.txt"

# These are intentionally left blank to rely on Ansible's default behavior.
# If you set the mode (permissions), USE QUOTES.
file_transfer_owning_user: null

file_transfer_dir_mode: null
file_transfer_file_mode: null
