---

- name: validate config filename
  ansible.builtin.assert:
    that: update_bash_config.file in ['.bashrc', '.bash_profile']
    fail_msg: "update_bash_config.file must be '.bashrc' or '.bash_profile', got {{ update_bash_config.file }}"
    success_msg: "update_bash_config.file is set to {{ update_bash_config.file }}"

- name: set config path variable for root user
  ansible.builtin.set_fact: 
    path: " {{ '/root/' ~ update_bash_config.file }} "
  when: update_bash_config.user == "root"

- name: set config path variable for non-root user
  ansible.builtin.set_fact: 
    path: "{{ '/home/' ~ update_bash_config.user ~ '/' ~ update_bash_config.file }}"
  when: update_bash_config.user != "root"

- name: update bash config on {{ ansible_hostname }}
  ansible.builtin.blockinfile:
    path: path
    create: true
    prepend_newline: true
    insertafter: EOF
    block: update_bash_config.block
