---
- name: limit SSH server to one session at a time
  ansible.builtin.lineinfile:
    path: /etc/security/limits.d/ansible.conf
    create: true
    line: "{{ limit_ssh_conn_user }} hard maxlogins 1"
