---
- name: install relevant packages
  ansible.builtin.package:
    name:
      - iptables
      - iptables-persistent
      - curl
    state: present
  become: yes # tells Ansible to do this section as root

- name: configure ICS firewall
  ansible.builtin.script: firewall.sh

